DROP TABLE IF EXISTS ANIMAL_DETAIL;
DROP TABLE IF EXISTS USERS;


CREATE TABLE USERS (
  USER_ID VARCHAR(50) PRIMARY KEY ,
  USER_FULL_NAME VARCHAR(50),
  PASSWORD VARCHAR(200) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE ANIMAL_DETAIL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ANIMAL_NAME VARCHAR(50) NOT NULL,
  ANIMAL_TYPE VARCHAR(50) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ROLES(
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY ,
  ROLE_NAME VARCHAR(45) NOT NULL
);

CREATE TABLE USERS_ROLES (
  USER_ID VARCHAR(50) NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

INSERT INTO ROLES( ROLE_ID, ROLE_NAME)
VALUES (1,'ROLE_USER');
INSERT INTO ROLES( ROLE_ID, ROLE_NAME)
VALUES (2,'ROLE_ADMIN');

INSERT INTO USERS( USER_ID, USER_FULL_NAME, PASSWORD, ENABLED)
VALUES ('AdminUser','Admin User','$2a$10$jFdKMru0aYwaAU1QWQrI6.58iokQq9Z0SzC3a6gzLXChKhA52a42W',true);

INSERT INTO USERS_ROLES(USER_ID, ROLE_ID)
VALUES ('AdminUser',1);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID)
VALUES ('AdminUser',2);



