DROP TABLE IF EXISTS ANIMAL_DETAIL;
DROP TABLE IF EXISTS USERS;


CREATE TABLE USERS (
  USER_ID VARCHAR(50) PRIMARY KEY ,
  USER_FULL_NAME VARCHAR(50),
  PASSWORD VARCHAR(200) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE ANIMAL_DETAIL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ANIMAL_NAME VARCHAR(50) NOT NULL,
  ANIMAL_TYPE VARCHAR(50) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ROLES(
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY ,
  ROLE_NAME VARCHAR(45) NOT NULL
);

CREATE TABLE USERS_ROLES (
  USER_ID VARCHAR(50) NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

INSERT INTO USERS( USER_ID, USER_FULL_NAME, PASSWORD, ENABLED)
VALUES ('city_edit','city user','$2a$10$rjGU/gWxsPMNF65UCaW.P.UtSPcosur.kcadI31hTDx.QT1GSHr6O',1);

INSERT INTO ROLES( ROLE_ID, ROLE_NAME)
VALUES (1,'ROLE_ALLOW_EDIT');

INSERT INTO USERS_ROLES(USER_ID, ROLE_ID)
VALUES ('city_edit',1);

INSERT INTO USERS( USER_ID, PASSWORD, ENABLED)
VALUES ('city_fetch','city_password',1);

INSERT INTO ANIMAL_DETAIL( ANIMAL_NAME, ANIMAL_TYPE, USER_ID)
VALUES ('Kitty','CAT','city_edit');

